name: CI - Lint

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["chore/add-ci-lint"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install ruff
        run: pip install ruff==0.5.6
      - name: Lint
        run: ruff check --output-format=github .
